### ISSUE TITLE
No Options Menu

### ISSUE THREAD

**Issue by UhuruNUru** [JustOff/advanced-night-mode#11]
I can't see this issue being affected by other extensions, though I do have around 40, but this is the only one that has an inactive options button.

The basic error is obvious, it has options, that can't be easily changed.

The options are still present in about config, and advanced users will be able to figure out how most work, being mainly just the colour settings in RGB format.

These two are not as obvious
Preference Name = extensions.AdvancedNightMode@Off.JustOff.default_method
Value = 1

Trial and error methods will likely show a limited number of options here, but I've not changed it.

Preference Name = **extensions.AdvancedNightMode@Off.JustOff.configured_pages**
Value = **{}**

Here with no idea of the exact format used, it's more difficult to guess the required values.
From the description, of per site settings, a URL (With RegEx ?), and it's RGB values.
Not going to be easy to figure out the correct format, from the default value.

I can live with the default settings, as much better than the awful glare the white background offers, to my valued single working eye. It would still be much better to have the Options GUI working, and be able to tweak things as required.

**Comment by JustOff** [comment]
The reason for this may be either incompatibility with another extension or a broken profile. I strongly advise you not to use the browser in this state, since then its behavior is uncertain and can lead to crashes and data loss.

As for the format in which the settings are stored in ANM, you can try to figure it out by examining the source code or experimenting in a separate clean profile.
