### ISSUE TITLE
Iceweasel-UXP / GUID

### ISSUE THREAD

**Issue by g4jc** [JustOff/advanced-night-mode#14]
Hello,
We have a user requesting `advanced-night-mode` support for Iceweasel-UXP.  I already confirmed it works perfectly once the GUID is added and there's no warnings in console. Would you be willing to add our GUID? If not we can still use a bundled package and apply the patch locally, but it would be nice for users to just be able to install the xpi. For any technical problems, users may ping us to help maintain it. However, I don't see any significant changes that would affect this addon as written.

```
        <em:targetApplication>
           <!-- Basilisk/Iceweasel-UXP -->
           <Description>
               <em:id>{ec8030f7-c20a-464f-9b0e-13a3a9e97384}</em:id>
               <em:minVersion>52.0</em:minVersion>
               <em:maxVersion>52.*</em:maxVersion>
           </Description>
        </em:targetApplication>
```

Thanks!

**Comment by JustOff** [comment]
I hate to admit it, but ANM is probably the most problematic addon I've ever made (actually forked, of course). Despite all my efforts, it still has a number of unresolved issues related to memory usage and performance. I wish I could rewrite it without [Add-ons SDK](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK), but it would require more time than I think reasonable to spend on this task.

That's why I deliberately [refused](https://github.com/JustOff/advanced-night-mode/issues/5) to support ANM for anything other than Pale Moon, even if it's known that it's working properly there at the moment. So, I'm sorry, but I will not make an exception for Iceweasel-UXP, especially considering that it shares its GUID with Basilisk and Firefox.

**Comment by FrostKnight** [comment]
Well, It least you gave a reason, its a shame, but oh well.

**Comment by Chirunos** [comment]
> I hate to admit it, but ANM is probably the most problematic addon I've ever made (actually forked, of course). Despite all my efforts, it still has a number of unresolved issues related to memory usage and performance. I wish I could rewrite it without [Add-ons SDK](https://developer.mozilla.org/en-US/docs/Archive/Add-ons/Add-on_SDK), but it would require more time than I think reasonable to spend on this task.
> 
> That's why I deliberately [refused](https://github.com/JustOff/advanced-night-mode/issues/5) to support ANM for anything other than Pale Moon, even if it's known that it's working properly there at the moment. So, I'm sorry, but I will not make an exception for Iceweasel-UXP, especially considering that it shares its GUID with Basilisk and Firefox.

Can you clarify this in the readme file?
