### ISSUE TITLE
Alters Palemoon Dialogs as well

### ISSUE THREAD

**Issue by AnthoniG** [JustOff/advanced-night-mode#2]
It's a great extension and very useful for my eyes. However I noticed that it alters all Palemoon Dialogs as well and it makes it impossible for me to see them.

If there was a way to have it so you can not activate on dialogs, then that would be perfect. Until then I have it disabled :disappointed:

**Comment by JustOff** [comment]
Could you please give me an example with a screenshot?

**Comment by AnthoniG** [comment]
https://imgur.com/a/r50fc --> Bookmark Edit
https://imgur.com/a/b94C2 -> LastPass Edit

**Comment by JustOff** [comment]
Hm... I can't reproduce it in my Win7 box with classic theme.

![2018-03-13_15-17-20](https://user-images.githubusercontent.com/340855/37343998-ff4e47e4-26c0-11e8-9341-970ff5fabdf5.png)

 What OS are you using?

**Comment by AnthoniG** [comment]
OS = Linux Mint 18 (Sylvia)
Theme = Walnutty 1.1.0

**Comment by AnthoniG** [comment]
If I disable the Walnutty theme then it does not alter the dialogs.
However it messes up All-In-One-Sidebar :cry:

**Comment by Lootyhoof** [comment]
Walnutty (as well as several other themes) do not use native styling for these elements, hence they are also affected by your styling. If you only want your extension to affect page content and not UI, you should add the HTML namespace to your CSS.

**Comment by JustOff** [comment]
Thank you @Lootyhoof, now I see.

@AnthoniG, open `chrome://browser/content/places/editBookmarkOverlay.xul` in a new tab and use ANM button to disable color processing for `chrome://browser` (or more specific path). Repeate these steps for `chrome://lastpass/content/lastpass.xul` and any other dialogues you have problem with.

**Comment by AnthoniG** [comment]
@JustOff 

Switching to SimpleCSS does the trick. Have not even had to add in the disable for any chrome:// paths. All I wanted to do was to be able to read the dialogs BUT still keep ANM active :grinning: 

If I still get trouble however I now have a direct fallback (disable certain chrome:// paths), so that is definitely something to keep in mind.

Thank you very much for your help.
Love your extension, saves me immense eye strain :smile: 

If want this can be closed now ?

**Comment by JustOff** [comment]
You are welcome.

**Comment by AnthoniG** [comment]
@JustOff 
One other quick question
How do I find the path for the extensions I want to 'disable / blacklist' ?

For example I need to do the chrome:// thing for Session Manager and I've tried

chrome://lastpass/content/session_manager.xul
chrome://lastpass/content/session.xul

etc and none worked.
Is there some place I can look this up please ?

**Comment by JustOff** [comment]
Look inside the extension package (I recommend [Extension Source Explorer](https://addons.palemoon.org/addon/esrc-explorer/) for this). Let's for example explore [Session Manager](https://addons.mozilla.org/addon/session-manager/): its `chrome.manifest` defines `sessionmanager` as the `content` prefix, so we can search by `chrome://sessionmanager/content` to find necessary xul overlays.

You can even manually edit `extensions.AdvancedNightMode@Off.JustOff.configured_pages` in `about:config`, but ANM need to be restarted (Disable/Enable) in order to apply changes. If you use `chrome://` pattern there, you can even change the processing mode for all existing overlays of the browser and extensions.

**Comment by AnthoniG** [comment]
Thanks for that.
Much appreciated.
